/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home_food_software;
//import  some java libraries-FD----------------------------------------------------------------------------------------------------------------------------------------------------
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isuru udana
 */
public class selection extends javax.swing.JFrame {
//-FD  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Connection conn= null;
    PreparedStatement pre =null;
    /**
     * Creates new form selection
     */
    public selection() {
        initComponents();
        show_user();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        selection_panal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customer_orders = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        database_login = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Food");
        setBackground(new java.awt.Color(255, 153, 51));

        parent_panel.setLayout(new java.awt.CardLayout());

        selection_panal.setLayout(null);

        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("See customer's orders");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        selection_panal.add(jButton1);
        jButton1.setBounds(310, 190, 230, 70);

        jButton2.setForeground(new java.awt.Color(102, 102, 0));
        jButton2.setText("Change the database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        selection_panal.add(jButton2);
        jButton2.setBounds(310, 270, 230, 70);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Select what do you want to do:");
        selection_panal.add(jLabel2);
        jLabel2.setBounds(100, 150, 370, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\isuru udana\\Desktop\\home\\2019.04.20\\photos\\bread_pastries_many_76629_1280x720.jpg")); // NOI18N
        selection_panal.add(jLabel1);
        jLabel1.setBounds(-2, -1, 810, 510);

        parent_panel.add(selection_panal, "card2");

        jButton3.setText("Go to home page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customerId", "riceId", "vegetableId1", "vegetableId2", "vegetableId3", "vegetableId4", "meat & fishId", "dessertId", "date", "time ", "Quntity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout customer_ordersLayout = new javax.swing.GroupLayout(customer_orders);
        customer_orders.setLayout(customer_ordersLayout);
        customer_ordersLayout.setHorizontalGroup(
            customer_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_ordersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_ordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        customer_ordersLayout.setVerticalGroup(
            customer_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_ordersLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(30, 30, 30))
        );

        parent_panel.add(customer_orders, "card4");

        jLabel4.setText("jLabel4");

        jButton4.setText("Go to home page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout database_loginLayout = new javax.swing.GroupLayout(database_login);
        database_login.setLayout(database_loginLayout);
        database_loginLayout.setHorizontalGroup(
            database_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, database_loginLayout.createSequentialGroup()
                .addContainerGap(635, Short.MAX_VALUE)
                .addGroup(database_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43))
        );
        database_loginLayout.setVerticalGroup(
            database_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(database_loginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(33, 33, 33))
        );

        parent_panel.add(database_login, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //got database_login panal-FD-----------------------------------------------------------------------------------------------------------------
        parent_panel.removeAll();
       parent_panel.add(database_login);
       parent_panel.repaint();
       parent_panel.revalidate();
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //goto customer_orders panal-FD--------------------------------------------------------------------------------------------------------------------------
       parent_panel.removeAll();
       parent_panel.add(customer_orders);
       parent_panel.repaint();
       parent_panel.revalidate();
       
       
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //again goto selection panal-FD--------------------------------------------------------------------------------------------------------------------------
           parent_panel.removeAll();
       parent_panel.add(selection_panal);
       parent_panel.repaint();
       parent_panel.revalidate();
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //again goto selection panal-FD--------------------------------------------------------------------------------------------------------------------------
           parent_panel.removeAll();
       parent_panel.add(selection_panal);
       parent_panel.repaint();
       parent_panel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void selectionmain(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel customer_orders;
    private javax.swing.JPanel database_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel parent_panel;
    private javax.swing.JPanel selection_panal;
    // End of variables declaration//GEN-END:variables
//---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    public ArrayList<order> orderList(){
        ArrayList<order>orderList =new ArrayList<>();
    try {
       
           conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
         //  pre=(PreparedStatement) conn.prepareStatement(sq1);
          String q="SELECT * FROM `orderd` WHERE 1";
          Statement st= conn.createStatement();
          ResultSet rs=st.executeQuery(q);
         order order1;
          while (rs.next()){
              order1= new order(rs.getInt("customerId"),rs.getInt("vegetableId1"),rs.getInt("vegetableId2"),rs.getInt("vegetableId3"),rs.getInt("vegetableId4"),
                  rs.getInt("meat_and_fishId"),rs.getInt("riceId"),rs.getInt("dessertId"), rs.getString("date"),rs.getString("time"),rs.getInt("Quntity"));
                 

               orderList.add(order1);
          }
        }
        catch (SQLException |HeadlessException ex ) {
            JOptionPane.showMessageDialog(null,ex);
        } return orderList;
    }
    public void show_user(){
  ArrayList<order> list = orderList();
  DefaultTableModel mode1=(DefaultTableModel)jTable1.getModel();
  Object[] row =new Object[11];for (int i=0;i<list.size();i++){
  row[0]=list.get(i).getcustomerId();
  row[1]=list.get(i). getriceId();
 row[2]=list.get(i).getvegetableId1();
  row[3]=list.get(i).getvegetableId2();
  row[4]=list.get(i).getvegetableId3();
  row[5]=list.get(i).getvegetableId4();
  row[6]=list.get(i).getmeat_and_fishId();
  row[7]=list.get(i). getdessertId();
  row[8]=list.get(i).getdate();
  row[9]=list.get(i).gettime();
  row[10]=list.get(i).getQuntity();
  
  mode1.addRow(row);
  }



}
}